[package]
name = "feynsum-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qasmsim = "1.3.0"
structopt = "0.3"
log = "0.4.20"
bit-vec = "0.6"
num = "0.4.1"
