#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

## NOTE: can use `jq -c` here to filter which rows you want to run.
## Remember to pass -c !
## (Compact output, ensures each line is a single json object.)
## For example:
##   $GEN | jq -c 'select(.input == "bv_n30.qasm") | $RUN ...'

$GEN $@ \
| $RUN --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
