#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
#NOW="231017-035001"
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

## NOTE: can use `jq -c` here to filter which rows you want to run.
## Remember to pass -c !
## (Compact output, ensures each line is a single json object.)
## For example:
##   $GEN | jq -c 'select(.input == "bv_n30.qasm") | $RUN ...'

(cd feynsum-sml && make)

$GEN -m r6i.32xlarge --trials 10 $@ \
| jq -c 'select(.simulator != "feynsum-rust")' \
| $RUN --timeout 1800 --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
